version: '3.8'

services:
  # 1. Your Prediction API (Pulled from Docker Hub)
  stock-api:
    image: noorulbaseer/stock-predictor:latest
    ports:
      - "8000:8000"
    networks:
      - monitoring-net

  # 2. Prometheus (The Collector)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

  # 3. Grafana (The Dashboard)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net

networks:
  monitoring-net: